import PDFDocument from "pdfkit";

export const createimpressaPDF = ({ title, contentBuilder, signatory, logoPath }) => {
  const doc = new PDFDocument({ margin: 50 });
  const pageWidth = doc.page.width;

  // 🧢 Header
  try {
    doc.image(logoPath, pageWidth / 2 - 30, 40, { width: 60 });
  } catch (err) {
    console.error("Logo failed to load:", err.message);
  }

  doc.moveDown(4);
  doc.fontSize(18).text("impressa Custom Solutions", { align: "center" });
  doc.fontSize(12).text(title, { align: "center" });
  doc.text(`Date: ${new Date().toLocaleDateString()}`, { align: "center" });
  doc.moveDown(2);

  // 📄 Content
  contentBuilder(doc);

  // ✍️ Signature & Stamp
  doc.moveDown(4);
  doc.fontSize(12).text("Approved by:", 50);
  doc.moveDown(1);
  doc.text(signatory.name, 50);
  doc.text(signatory.title, 50);
  doc.moveDown(2);

  if (signatory.signatureImage) {
    try {
      doc.image(signatory.signatureImage, 50, doc.y, { width: 100 });
      doc.moveDown(2);
    } catch {
      doc.text("Signature: ______________________", 50);
      doc.moveDown(2);
    }
  } else {
    doc.text("Signature: ______________________", 50);
    doc.moveDown(2);
  }

  if (signatory.stampImage) {
    try {
      doc.image(signatory.stampImage, 50, doc.y, { width: 100 });
      doc.moveDown(2);
    } catch {
      doc.text("Stamp:     ______________________", 50);
      doc.moveDown(2);
    }
  } else {
    doc.text("Stamp:     ______________________", 50);
    doc.moveDown(2);
  }

  // 📄 Footer
  const footerY = doc.page.height - doc.page.margins.bottom - 40;
  doc.fontSize(10).text("Generated by impressa Admin Dashboard", doc.page.margins.left, footerY, {
    align: "center",
    width: pageWidth - doc.page.margins.left - doc.page.margins.right,
  });
  doc.text(`Report generated on ${new Date().toLocaleString()}`, {
    align: "center",
    width: pageWidth - doc.page.margins.left - doc.page.margins.right,
  });

  return doc;
};