import PDFDocument from "pdfkit";
import generateUserTablePDF from "../utils/userTablePDF.js";
export const generateUserTablePDF = (userRows) => {
  const doc = new PDFDocument({ margin: 50 });
  const pageWidth = doc.page.width;

  // 🏷️ Header
  doc.fontSize(18).text("impressa Custom Solutions", { align: "center" });
  doc.fontSize(12).text("User Table Report", { align: "center" });
  doc.text(`Date: ${new Date().toLocaleDateString()}`, { align: "center" });
  doc.moveDown(2);

  // 📋 Table Header
  const columns = [
    { label: "Name", x: 50 },
    { label: "Email", x: 200 },
    { label: "Role", x: 370 },
    { label: "Created At", x: 450 },
  ];

  doc.font("Helvetica-Bold").fontSize(10);
  const headerY = doc.y;
  columns.forEach(col => doc.text(col.label, col.x, headerY));
  doc.moveDown(0.5);

  // 👤 Table Rows
  doc.font("Helvetica").fontSize(10);
  userRows.forEach(user => {
    const y = doc.y;
    doc.text(user.name || "", columns[0].x, y);
    doc.text(user.email || "", columns[1].x, y);
    doc.text(user.role || "", columns[2].x, y);
    doc.text(new Date(user.createdAt).toLocaleDateString(), columns[3].x, y);
    doc.moveDown(0.5);
  });

  // 📄 Footer
  const footerY = doc.page.height - doc.page.margins.bottom - 40;
  doc.fontSize(10).text("Generated by impressa Admin Dashboard", doc.page.margins.left, footerY, {
    align: "center",
    width: pageWidth - doc.page.margins.left - doc.page.margins.right,
  });
  doc.text(`Report generated on ${new Date().toLocaleString()}`, {
    align: "center",
    width: pageWidth - doc.page.margins.left - doc.page.margins.right,
  });

  return doc;
};